services:
#Application
  app:
    image: keyloop-test
    container_name: keyloop-test-app
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      REDIS_ADDR: ${REDIS_ADDR}
    networks:
      - keyloop-test-network
    depends_on:
       postgresql:
        condition: service_healthy
       redis:
        condition: service_healthy

#Postgres 
  postgresql:
    image: postgres:15.3
    container_name: keyloop-test-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - keyloop-test-postgresql-data:/var/lib/keyloop-test/postgresql-data
    networks:
      - keyloop-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7.2.0
    container_name: keyloop-test-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - keyloop-test-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  

volumes:
  keyloop-test-postgresql-data:
    name: keyloop-test-postgresql-data
networks:
  keyloop-test-network:
    driver: bridge
    name: keyloop-test-network
