// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AppointmentStatus string

const (
	AppointmentStatusPending   AppointmentStatus = "pending"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusCompleted AppointmentStatus = "completed"
	AppointmentStatusNoShow    AppointmentStatus = "no_show"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	Valid             bool              `json:"valid"` // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type BayStatus string

const (
	BayStatusActive      BayStatus = "active"
	BayStatusInactive    BayStatus = "inactive"
	BayStatusMaintenance BayStatus = "maintenance"
)

func (e *BayStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BayStatus(s)
	case string:
		*e = BayStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BayStatus: %T", src)
	}
	return nil
}

type NullBayStatus struct {
	BayStatus BayStatus `json:"bay_status"`
	Valid     bool      `json:"valid"` // Valid is true if BayStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBayStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BayStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BayStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBayStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BayStatus), nil
}

type TechnicianStatus string

const (
	TechnicianStatusActive   TechnicianStatus = "active"
	TechnicianStatusInactive TechnicianStatus = "inactive"
	TechnicianStatusOnLeave  TechnicianStatus = "on_leave"
)

func (e *TechnicianStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TechnicianStatus(s)
	case string:
		*e = TechnicianStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TechnicianStatus: %T", src)
	}
	return nil
}

type NullTechnicianStatus struct {
	TechnicianStatus TechnicianStatus `json:"technician_status"`
	Valid            bool             `json:"valid"` // Valid is true if TechnicianStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTechnicianStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TechnicianStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TechnicianStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTechnicianStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TechnicianStatus), nil
}

type Appointment struct {
	ID           uuid.UUID         `json:"id"`
	CustomerID   uuid.UUID         `json:"customer_id"`
	VehicleID    uuid.UUID         `json:"vehicle_id"`
	DealershipID uuid.UUID         `json:"dealership_id"`
	ServiceBayID uuid.UUID         `json:"service_bay_id"`
	TechnicianID uuid.UUID         `json:"technician_id"`
	Services     json.RawMessage   `json:"services"`
	Status       AppointmentStatus `json:"status"`
	StartTime    time.Time         `json:"start_time"`
	EndTime      time.Time         `json:"end_time"`
	Notes        sql.NullString    `json:"notes"`
	DeletedAt    sql.NullTime      `json:"deleted_at"`
	CreatedAt    time.Time         `json:"created_at"`
	UpdatedAt    time.Time         `json:"updated_at"`
}

type Customer struct {
	ID        uuid.UUID    `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Email     string       `json:"email"`
	Phone     string       `json:"phone"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Dealership struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Address   string       `json:"address"`
	City      string       `json:"city"`
	Phone     string       `json:"phone"`
	IsActive  bool         `json:"is_active"`
	OpenTime  time.Time    `json:"open_time"`
	CloseTime time.Time    `json:"close_time"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type ServiceBay struct {
	ID           uuid.UUID    `json:"id"`
	DealershipID uuid.UUID    `json:"dealership_id"`
	Name         string       `json:"name"`
	BayNumber    int32        `json:"bay_number"`
	Status       BayStatus    `json:"status"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type ServiceDefinition struct {
	ID               uuid.UUID    `json:"id"`
	Name             string       `json:"name"`
	Description      string       `json:"description"`
	EstimatedMinutes int32        `json:"estimated_minutes"`
	Price            string       `json:"price"`
	IsActive         bool         `json:"is_active"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

type Technician struct {
	ID           uuid.UUID        `json:"id"`
	DealershipID uuid.UUID        `json:"dealership_id"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	Status       TechnicianStatus `json:"status"`
	DeletedAt    sql.NullTime     `json:"deleted_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

type TechnicianSkill struct {
	TechnicianID        uuid.UUID `json:"technician_id"`
	ServiceDefinitionID uuid.UUID `json:"service_definition_id"`
}

type Vehicle struct {
	ID           uuid.UUID    `json:"id"`
	CustomerID   uuid.UUID    `json:"customer_id"`
	Make         string       `json:"make"`
	Model        string       `json:"model"`
	Year         int32        `json:"year"`
	Vin          string       `json:"vin"`
	LicensePlate string       `json:"license_plate"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}
