// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAppointment = `-- name: CreateAppointment :one

WITH slot_range AS (
  SELECT tstzrange(
    $4::TIMESTAMPTZ,
    $5::TIMESTAMPTZ
  ) AS range
),
available_bay AS (
  SELECT b.id
  FROM service_bays b, slot_range sr
  WHERE b.dealership_id = $1
    AND NOT EXISTS (
      SELECT 1 FROM appointments a
      WHERE a.service_bay_id = b.id
        AND a.dealership_id = $1
        AND a.status <> 'cancelled'
        AND tstzrange(a.start_time, a.end_time) && sr.range
    )
  LIMIT 1
  FOR UPDATE SKIP LOCKED
),
available_technician AS (
  SELECT t.id
  FROM technicians t, slot_range sr
  WHERE t.dealership_id = $1
    AND t.id IN (
      SELECT technician_id FROM technician_skills
      WHERE service_id::text = ANY($9::text[])
      GROUP BY technician_id
      HAVING COUNT(DISTINCT service_id) = cardinality($9::text[])
    )
    AND NOT EXISTS (
      SELECT 1 FROM appointments a
      WHERE a.technician_id = t.id
        AND a.dealership_id = $1
        AND a.status <> 'cancelled'
        AND tstzrange(a.start_time, a.end_time) && sr.range
    )
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
INSERT INTO appointments (
  dealership_id, customer_id, vehicle_id,
  service_bay_id, technician_id,
  start_time, end_time,
  status, notes, services
)
SELECT
  $1,
  $2,
  $3,
  availbay.id,
  availtech.id,
  $4::TIMESTAMPTZ,
  $5::TIMESTAMPTZ,
  $6::appointment_status,
  $7,
  $8::JSONB

FROM available_bay availbay, available_technician availtech
RETURNING id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at
`

type CreateAppointmentParams struct {
	DealershipID uuid.UUID         `json:"dealership_id"`
	CustomerID   uuid.UUID         `json:"customer_id"`
	VehicleID    uuid.UUID         `json:"vehicle_id"`
	StartTime    time.Time         `json:"start_time"`
	EndTime      time.Time         `json:"end_time"`
	Status       AppointmentStatus `json:"status"`
	Notes        sql.NullString    `json:"notes"`
	Services     json.RawMessage   `json:"services"`
	ServiceIds   []string          `json:"service_ids"`
}

// Service_ids input to fetch technicians with all required skills and to check bay/tech availability
// Services input to store snapshot of service details at time of booking (name, price, duration) to prevent issues if service definitions change later
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.DealershipID,
		arg.CustomerID,
		arg.VehicleID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Notes,
		arg.Services,
		pq.Array(arg.ServiceIds),
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.ServiceBayID,
		&i.TechnicianID,
		&i.Services,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  id, first_name, last_name, email, phone
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, first_name, last_name, email, phone, deleted_at, created_at, updated_at
`

type CreateCustomerParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDealership = `-- name: CreateDealership :one
INSERT INTO dealerships (
  id, name, address, city, phone, is_active, open_time, close_time, working_days
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, address, city, phone, is_active, open_time, close_time, working_days, deleted_at, created_at, updated_at
`

type CreateDealershipParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Address     string    `json:"address"`
	City        string    `json:"city"`
	Phone       string    `json:"phone"`
	IsActive    bool      `json:"is_active"`
	OpenTime    time.Time `json:"open_time"`
	CloseTime   time.Time `json:"close_time"`
	WorkingDays []int32   `json:"working_days"`
}

func (q *Queries) CreateDealership(ctx context.Context, arg CreateDealershipParams) (Dealership, error) {
	row := q.db.QueryRowContext(ctx, createDealership,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Phone,
		arg.IsActive,
		arg.OpenTime,
		arg.CloseTime,
		pq.Array(arg.WorkingDays),
	)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Phone,
		&i.IsActive,
		&i.OpenTime,
		&i.CloseTime,
		pq.Array(&i.WorkingDays),
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
  id, name, description, estimated_minutes, price, is_active
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, name, description, estimated_minutes, price, is_active, deleted_at, created_at, updated_at
`

type CreateServiceParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	EstimatedMinutes int32     `json:"estimated_minutes"`
	Price            string    `json:"price"`
	IsActive         bool      `json:"is_active"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.EstimatedMinutes,
		arg.Price,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EstimatedMinutes,
		&i.Price,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceBay = `-- name: CreateServiceBay :one
INSERT INTO service_bays (
  id, dealership_id, name, bay_number, status
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, dealership_id, name, bay_number, status, deleted_at, created_at, updated_at
`

type CreateServiceBayParams struct {
	ID           uuid.UUID `json:"id"`
	DealershipID uuid.UUID `json:"dealership_id"`
	Name         string    `json:"name"`
	BayNumber    int32     `json:"bay_number"`
	Status       BayStatus `json:"status"`
}

func (q *Queries) CreateServiceBay(ctx context.Context, arg CreateServiceBayParams) (ServiceBay, error) {
	row := q.db.QueryRowContext(ctx, createServiceBay,
		arg.ID,
		arg.DealershipID,
		arg.Name,
		arg.BayNumber,
		arg.Status,
	)
	var i ServiceBay
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.BayNumber,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTechnician = `-- name: CreateTechnician :one
INSERT INTO technicians (
  id, dealership_id, first_name, last_name, status
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, dealership_id, first_name, last_name, status, deleted_at, created_at, updated_at
`

type CreateTechnicianParams struct {
	ID           uuid.UUID        `json:"id"`
	DealershipID uuid.UUID        `json:"dealership_id"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	Status       TechnicianStatus `json:"status"`
}

func (q *Queries) CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (Technician, error) {
	row := q.db.QueryRowContext(ctx, createTechnician,
		arg.ID,
		arg.DealershipID,
		arg.FirstName,
		arg.LastName,
		arg.Status,
	)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTechnicianSkill = `-- name: CreateTechnicianSkill :exec
INSERT INTO technician_skills (
  technician_id, service_id
) VALUES (
  $1, $2
)
`

type CreateTechnicianSkillParams struct {
	TechnicianID uuid.UUID `json:"technician_id"`
	ServiceID    uuid.UUID `json:"service_id"`
}

func (q *Queries) CreateTechnicianSkill(ctx context.Context, arg CreateTechnicianSkillParams) error {
	_, err := q.db.ExecContext(ctx, createTechnicianSkill, arg.TechnicianID, arg.ServiceID)
	return err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
  id, customer_id, make, model, year, vin, license_plate
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, customer_id, make, model, year, vin, license_plate, deleted_at, created_at, updated_at
`

type CreateVehicleParams struct {
	ID           uuid.UUID `json:"id"`
	CustomerID   uuid.UUID `json:"customer_id"`
	Make         string    `json:"make"`
	Model        string    `json:"model"`
	Year         int32     `json:"year"`
	Vin          string    `json:"vin"`
	LicensePlate string    `json:"license_plate"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.ID,
		arg.CustomerID,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Vin,
		arg.LicensePlate,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Vin,
		&i.LicensePlate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const deleteDealership = `-- name: DeleteDealership :exec
DELETE FROM dealerships WHERE id = $1
`

func (q *Queries) DeleteDealership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDealership, id)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const deleteServiceBay = `-- name: DeleteServiceBay :exec
DELETE FROM service_bays WHERE id = $1
`

func (q *Queries) DeleteServiceBay(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteServiceBay, id)
	return err
}

const deleteTechnician = `-- name: DeleteTechnician :exec
DELETE FROM technicians WHERE id = $1
`

func (q *Queries) DeleteTechnician(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTechnician, id)
	return err
}

const deleteTechnicianSkill = `-- name: DeleteTechnicianSkill :exec
  DELETE FROM technician_skills WHERE technician_id = $1 AND service_id = $2
`

type DeleteTechnicianSkillParams struct {
	TechnicianID uuid.UUID `json:"technician_id"`
	ServiceID    uuid.UUID `json:"service_id"`
}

func (q *Queries) DeleteTechnicianSkill(ctx context.Context, arg DeleteTechnicianSkillParams) error {
	_, err := q.db.ExecContext(ctx, deleteTechnicianSkill, arg.TechnicianID, arg.ServiceID)
	return err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVehicle, id)
	return err
}

const getAppointment = `-- name: GetAppointment :one

SELECT id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at FROM appointments WHERE id = $1
`

// =========================================================================
// APPOINTMENTS (Remaining CRUD)
// =========================================================================
func (q *Queries) GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.ServiceBayID,
		&i.TechnicianID,
		&i.Services,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableSlots = `-- name: GetAvailableSlots :many
SELECT slot::TIMESTAMP WITH TIME ZONE
FROM generate_series(
  $1::TIMESTAMP WITH TIME ZONE,
  $2::TIMESTAMP WITH TIME ZONE,
  '30 minutes'::INTERVAL
) AS slot
WHERE
  -- At least 1 bay is free for the full duration
  EXISTS (
    SELECT 1 FROM service_bays b
    WHERE b.dealership_id = $3
    AND b.id NOT IN (
      SELECT service_bay_id FROM appointments
      WHERE status IN ('pending', 'confirmed')
      AND tstzrange(start_time, end_time) &&
            tstzrange(slot, slot + $4::INTERVAL)
    )
  )
  AND
  -- At least 1 technician who has ALL required skills and is free for the full duration
  EXISTS (
    SELECT 1 FROM technicians t
    WHERE t.dealership_id = $3
    AND t.id IN (
      -- tech must have ALL required skills
      SELECT technician_id FROM technician_skills
      WHERE service_id::text = ANY($5::text[])
      GROUP BY technician_id
      HAVING COUNT(DISTINCT service_id) = cardinality($5::text[])
    )
    AND t.id NOT IN (
      SELECT technician_id FROM appointments
      WHERE status IN ('pending', 'confirmed')
      AND tstzrange(start_time, end_time) &&
            tstzrange(slot, slot + $4::INTERVAL)
    )
  )
ORDER BY slot ASC
`

type GetAvailableSlotsParams struct {
	StartDatetime time.Time `json:"start_datetime"`
	EndDatetime   time.Time `json:"end_datetime"`
	DealershipID  uuid.UUID `json:"dealership_id"`
	Duration      int64     `json:"duration"`
	ServiceTypes  []string  `json:"service_types"`
}

func (q *Queries) GetAvailableSlots(ctx context.Context, arg GetAvailableSlotsParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableSlots,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.DealershipID,
		arg.Duration,
		pq.Array(arg.ServiceTypes),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var slot time.Time
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one


SELECT id, first_name, last_name, email, phone, deleted_at, created_at, updated_at FROM customers WHERE id = $1
`

// =========================================================================
// CUSTOMERS
// =========================================================================
func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealership = `-- name: GetDealership :one

SELECT id, name, address, city, phone, is_active, open_time, close_time, working_days, deleted_at, created_at, updated_at FROM dealerships WHERE id = $1
`

// =========================================================================
// DEALERSHIPS
// =========================================================================
func (q *Queries) GetDealership(ctx context.Context, id uuid.UUID) (Dealership, error) {
	row := q.db.QueryRowContext(ctx, getDealership, id)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Phone,
		&i.IsActive,
		&i.OpenTime,
		&i.CloseTime,
		pq.Array(&i.WorkingDays),
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one

SELECT id, name, description, estimated_minutes, price, is_active, deleted_at, created_at, updated_at FROM services WHERE id = $1
`

// =========================================================================
// SERVICE
// =========================================================================
func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EstimatedMinutes,
		&i.Price,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBay = `-- name: GetServiceBay :one

SELECT id, dealership_id, name, bay_number, status, deleted_at, created_at, updated_at FROM service_bays WHERE id = $1
`

// =========================================================================
// SERVICE BAYS
// =========================================================================
func (q *Queries) GetServiceBay(ctx context.Context, id uuid.UUID) (ServiceBay, error) {
	row := q.db.QueryRowContext(ctx, getServiceBay, id)
	var i ServiceBay
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.BayNumber,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechnician = `-- name: GetTechnician :one

SELECT id, dealership_id, first_name, last_name, status, deleted_at, created_at, updated_at FROM technicians WHERE id = $1
`

// =========================================================================
// TECHNICIANS
// =========================================================================
func (q *Queries) GetTechnician(ctx context.Context, id uuid.UUID) (Technician, error) {
	row := q.db.QueryRowContext(ctx, getTechnician, id)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicle = `-- name: GetVehicle :one

SELECT id, customer_id, make, model, year, vin, license_plate, deleted_at, created_at, updated_at FROM vehicles WHERE id = $1
`

// =========================================================================
// VEHICLES
// =========================================================================
func (q *Queries) GetVehicle(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Vin,
		&i.LicensePlate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentsByCustomer = `-- name: ListAppointmentsByCustomer :many
SELECT id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at FROM appointments WHERE customer_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListAppointmentsByCustomer(ctx context.Context, customerID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.DealershipID,
			&i.ServiceBayID,
			&i.TechnicianID,
			&i.Services,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByCustomerAndDealership = `-- name: ListAppointmentsByCustomerAndDealership :many
SELECT id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at FROM appointments WHERE customer_id = $1 AND dealership_id = $2 ORDER BY start_time DESC
`

type ListAppointmentsByCustomerAndDealershipParams struct {
	CustomerID   uuid.UUID `json:"customer_id"`
	DealershipID uuid.UUID `json:"dealership_id"`
}

func (q *Queries) ListAppointmentsByCustomerAndDealership(ctx context.Context, arg ListAppointmentsByCustomerAndDealershipParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByCustomerAndDealership, arg.CustomerID, arg.DealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.DealershipID,
			&i.ServiceBayID,
			&i.TechnicianID,
			&i.Services,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDealership = `-- name: ListAppointmentsByDealership :many
SELECT id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at FROM appointments WHERE dealership_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListAppointmentsByDealership(ctx context.Context, dealershipID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByDealership, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.DealershipID,
			&i.ServiceBayID,
			&i.TechnicianID,
			&i.Services,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, first_name, last_name, email, phone, deleted_at, created_at, updated_at FROM customers ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealerships = `-- name: ListDealerships :many
SELECT id, name, address, city, phone, is_active, open_time, close_time, working_days, deleted_at, created_at, updated_at FROM dealerships ORDER BY name ASC
`

func (q *Queries) ListDealerships(ctx context.Context) ([]Dealership, error) {
	rows, err := q.db.QueryContext(ctx, listDealerships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dealership
	for rows.Next() {
		var i Dealership
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Phone,
			&i.IsActive,
			&i.OpenTime,
			&i.CloseTime,
			pq.Array(&i.WorkingDays),
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBaysByDealership = `-- name: ListServiceBaysByDealership :many
SELECT id, dealership_id, name, bay_number, status, deleted_at, created_at, updated_at FROM service_bays WHERE dealership_id = $1 ORDER BY bay_number ASC
`

func (q *Queries) ListServiceBaysByDealership(ctx context.Context, dealershipID uuid.UUID) ([]ServiceBay, error) {
	rows, err := q.db.QueryContext(ctx, listServiceBaysByDealership, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceBay
	for rows.Next() {
		var i ServiceBay
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.Name,
			&i.BayNumber,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, estimated_minutes, price, is_active, deleted_at, created_at, updated_at FROM services ORDER BY name ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.EstimatedMinutes,
			&i.Price,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechnicianSkills = `-- name: ListTechnicianSkills :many

SELECT technician_id, service_id FROM technician_skills WHERE technician_id = $1
`

// =========================================================================
// TECHNICIAN SKILLS
// =========================================================================
func (q *Queries) ListTechnicianSkills(ctx context.Context, technicianID uuid.UUID) ([]TechnicianSkill, error) {
	rows, err := q.db.QueryContext(ctx, listTechnicianSkills, technicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechnicianSkill
	for rows.Next() {
		var i TechnicianSkill
		if err := rows.Scan(&i.TechnicianID, &i.ServiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechniciansByDealership = `-- name: ListTechniciansByDealership :many
SELECT id, dealership_id, first_name, last_name, status, deleted_at, created_at, updated_at FROM technicians WHERE dealership_id = $1 ORDER BY first_name ASC
`

func (q *Queries) ListTechniciansByDealership(ctx context.Context, dealershipID uuid.UUID) ([]Technician, error) {
	rows, err := q.db.QueryContext(ctx, listTechniciansByDealership, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Technician
	for rows.Next() {
		var i Technician
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByCustomer = `-- name: ListVehiclesByCustomer :many
SELECT id, customer_id, make, model, year, vin, license_plate, deleted_at, created_at, updated_at FROM vehicles WHERE customer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVehiclesByCustomer(ctx context.Context, customerID uuid.UUID) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, listVehiclesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Vin,
			&i.LicensePlate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, vehicle_id, dealership_id, service_bay_id, technician_id, services, status, start_time, end_time, notes, deleted_at, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status AppointmentStatus `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.ServiceBayID,
		&i.TechnicianID,
		&i.Services,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, deleted_at, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDealership = `-- name: UpdateDealership :one
UPDATE dealerships
SET name = $2,
    address = $3,
    city = $4,
    phone = $5,
    is_active = $6,
    open_time = $7,
    close_time = $8,
    working_days = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, city, phone, is_active, open_time, close_time, working_days, deleted_at, created_at, updated_at
`

type UpdateDealershipParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Address     string    `json:"address"`
	City        string    `json:"city"`
	Phone       string    `json:"phone"`
	IsActive    bool      `json:"is_active"`
	OpenTime    time.Time `json:"open_time"`
	CloseTime   time.Time `json:"close_time"`
	WorkingDays []int32   `json:"working_days"`
}

func (q *Queries) UpdateDealership(ctx context.Context, arg UpdateDealershipParams) (Dealership, error) {
	row := q.db.QueryRowContext(ctx, updateDealership,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Phone,
		arg.IsActive,
		arg.OpenTime,
		arg.CloseTime,
		pq.Array(arg.WorkingDays),
	)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Phone,
		&i.IsActive,
		&i.OpenTime,
		&i.CloseTime,
		pq.Array(&i.WorkingDays),
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services 
SET name = $2,
    description = $3,
    estimated_minutes = $4,
    price = $5,
    is_active = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, estimated_minutes, price, is_active, deleted_at, created_at, updated_at
`

type UpdateServiceParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	EstimatedMinutes int32     `json:"estimated_minutes"`
	Price            string    `json:"price"`
	IsActive         bool      `json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.EstimatedMinutes,
		arg.Price,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EstimatedMinutes,
		&i.Price,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceBay = `-- name: UpdateServiceBay :one
UPDATE service_bays
SET name = $2,
    bay_number = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, dealership_id, name, bay_number, status, deleted_at, created_at, updated_at
`

type UpdateServiceBayParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	BayNumber int32     `json:"bay_number"`
	Status    BayStatus `json:"status"`
}

func (q *Queries) UpdateServiceBay(ctx context.Context, arg UpdateServiceBayParams) (ServiceBay, error) {
	row := q.db.QueryRowContext(ctx, updateServiceBay,
		arg.ID,
		arg.Name,
		arg.BayNumber,
		arg.Status,
	)
	var i ServiceBay
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.BayNumber,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTechnician = `-- name: UpdateTechnician :one
UPDATE technicians
SET first_name = $2,
    last_name = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, dealership_id, first_name, last_name, status, deleted_at, created_at, updated_at
`

type UpdateTechnicianParams struct {
	ID        uuid.UUID        `json:"id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Status    TechnicianStatus `json:"status"`
}

func (q *Queries) UpdateTechnician(ctx context.Context, arg UpdateTechnicianParams) (Technician, error) {
	row := q.db.QueryRowContext(ctx, updateTechnician,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Status,
	)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET make = $2,
    model = $3,
    year = $4,
    vin = $5,
    license_plate = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, make, model, year, vin, license_plate, deleted_at, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID           uuid.UUID `json:"id"`
	Make         string    `json:"make"`
	Model        string    `json:"model"`
	Year         int32     `json:"year"`
	Vin          string    `json:"vin"`
	LicensePlate string    `json:"license_plate"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, updateVehicle,
		arg.ID,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Vin,
		arg.LicensePlate,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Vin,
		&i.LicensePlate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
