// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Service_ids input to fetch technicians with all required skills and to check bay/tech availability
	// Services input to store snapshot of service details at time of booking (name, price, duration) to prevent issues if service definitions change later
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDealership(ctx context.Context, arg CreateDealershipParams) (Dealership, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceBay(ctx context.Context, arg CreateServiceBayParams) (ServiceBay, error)
	CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (Technician, error)
	CreateTechnicianSkill(ctx context.Context, arg CreateTechnicianSkillParams) error
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	DeleteAppointment(ctx context.Context, id uuid.UUID) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	DeleteDealership(ctx context.Context, id uuid.UUID) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteServiceBay(ctx context.Context, id uuid.UUID) error
	DeleteTechnician(ctx context.Context, id uuid.UUID) error
	DeleteTechnicianSkill(ctx context.Context, arg DeleteTechnicianSkillParams) error
	DeleteVehicle(ctx context.Context, id uuid.UUID) error
	// Picks the alphabetically-first active technician who holds ALL requested
	// skills and has no confirmed/pending appointment overlapping [start_time, end_time),
	// paired with the lowest-numbered active bay in the same dealership that is
	// also free during that interval.
	// Returns zero rows (sql.ErrNoRows) when no valid pair exists.
	FindAvailableTechnicianAndBay(ctx context.Context, arg FindAvailableTechnicianAndBayParams) (FindAvailableTechnicianAndBayRow, error)
	// =========================================================================
	// APPOINTMENTS (Remaining CRUD)
	// =========================================================================
	GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error)
	GetAvailableServiceBays(ctx context.Context, arg GetAvailableServiceBaysParams) ([]ServiceBay, error)
	GetAvailableSlots(ctx context.Context, arg GetAvailableSlotsParams) ([]time.Time, error)
	GetAvailableTechnicians(ctx context.Context, arg GetAvailableTechniciansParams) ([]Technician, error)
	//
	// =========================================================================
	// CUSTOMERS
	// =========================================================================
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	// =========================================================================
	// DEALERSHIPS
	// =========================================================================
	GetDealership(ctx context.Context, id uuid.UUID) (Dealership, error)
	// =========================================================================
	// SERVICE
	// =========================================================================
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	// =========================================================================
	// SERVICE BAYS
	// =========================================================================
	GetServiceBay(ctx context.Context, id uuid.UUID) (ServiceBay, error)
	// =========================================================================
	// TECHNICIANS
	// =========================================================================
	GetTechnician(ctx context.Context, id uuid.UUID) (Technician, error)
	// =========================================================================
	// VEHICLES
	// =========================================================================
	GetVehicle(ctx context.Context, id uuid.UUID) (Vehicle, error)
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (Appointment, error)
	ListAppointmentsByCustomer(ctx context.Context, customerID uuid.UUID) ([]Appointment, error)
	ListAppointmentsByCustomerAndDealership(ctx context.Context, arg ListAppointmentsByCustomerAndDealershipParams) ([]Appointment, error)
	ListAppointmentsByDealership(ctx context.Context, dealershipID uuid.UUID) ([]Appointment, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListDealerships(ctx context.Context) ([]Dealership, error)
	ListServiceBaysByDealership(ctx context.Context, dealershipID uuid.UUID) ([]ServiceBay, error)
	ListServices(ctx context.Context) ([]Service, error)
	// =========================================================================
	// TECHNICIAN SKILLS
	// =========================================================================
	ListTechnicianSkills(ctx context.Context, technicianID uuid.UUID) ([]TechnicianSkill, error)
	ListTechniciansByDealership(ctx context.Context, dealershipID uuid.UUID) ([]Technician, error)
	ListVehiclesByCustomer(ctx context.Context, customerID uuid.UUID) ([]Vehicle, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateDealership(ctx context.Context, arg UpdateDealershipParams) (Dealership, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceBay(ctx context.Context, arg UpdateServiceBayParams) (ServiceBay, error)
	UpdateTechnician(ctx context.Context, arg UpdateTechnicianParams) (Technician, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
}

var _ Querier = (*Queries)(nil)
